-- =====================================================================
-- Unified Neuro Platform — COMPLETE database setup (one file).
--
-- Paste this ENTIRE file into the Supabase SQL Editor and run it once.
-- It is IDEMPOTENT: safe to run multiple times (uses IF NOT EXISTS /
-- DROP POLICY IF EXISTS / ON CONFLICT DO NOTHING). It does NOT drop tables
-- or delete data.
--
-- It creates exactly what the MERGED (unified `platform/`) app needs:
--   1. Extensions
--   2. Lookup tables (blood_groups, qualifications) + starter values
--   3. Identity schema (hospitals, user_profiles, role profiles, relationships)
--   4. Simple RLS so the frontend AuthProvider can read profiles
--   5. Unified analysis tables (analysis_sessions/results/reports/job_events)
--   6. Private storage buckets
--
-- It intentionally EXCLUDES the legacy per-app analysis tables
-- (predictions, eeg_sessions, mri_sessions, ...) — the unified backend does
-- not use them. If you also want to run the OLD standalone apps, create those
-- separately from their own schema docs.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Extensions
-- ---------------------------------------------------------------------
create extension if not exists "pgcrypto";     -- gen_random_uuid()
create extension if not exists "uuid-ossp";     -- uuid_generate_v4() (legacy defaults)

-- ---------------------------------------------------------------------
-- 2. Lookup tables + starter data
-- ---------------------------------------------------------------------
create table if not exists public.blood_groups (
  id integer generated by default as identity primary key,
  blood_type varchar not null unique
);

create table if not exists public.qualifications (
  id integer generated by default as identity primary key,
  qualification_name varchar not null unique,
  specialization varchar
);

insert into public.blood_groups (blood_type) values
  ('A+'),('A-'),('B+'),('B-'),('AB+'),('AB-'),('O+'),('O-')
on conflict (blood_type) do nothing;

insert into public.qualifications (qualification_name, specialization) values
  ('MBBS', 'General Medicine'),
  ('MD Neurology', 'Neurology'),
  ('MD Radiology', 'Radiology'),
  ('DM Neurology', 'Neurology')
on conflict (qualification_name) do nothing;

-- ---------------------------------------------------------------------
-- 3. Identity schema
-- ---------------------------------------------------------------------
create table if not exists public.hospitals (
  id uuid primary key default gen_random_uuid(),
  hospital_code varchar not null unique,
  name varchar not null,
  address text not null,
  phone varchar,
  email varchar,
  license_number varchar,
  established_date date,
  status varchar not null default 'active'
    check (status in ('active','inactive','suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  hospital_id uuid not null references public.hospitals(id),
  unique_identifier varchar not null unique,
  full_name varchar not null,
  email varchar not null unique,
  phone varchar not null,
  date_of_birth date,
  address text,
  role varchar not null,
  account_status varchar not null default 'pending'
    check (account_status in ('pending','active','suspended','inactive')),
  auth_provider varchar default 'email',
  created_by_admin uuid references public.user_profiles(id),
  first_login_required boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Widen the role CHECK to the full consolidated set of 5 roles (also fixes an
-- existing project whose user_profiles still uses the 4-role legacy CHECK).
alter table public.user_profiles drop constraint if exists user_profiles_role_check;
alter table public.user_profiles
  add constraint user_profiles_role_check
  check (role in ('admin','doctor','radiologist','technician','patient'));

create table if not exists public.patient_profiles (
  user_id uuid primary key references public.user_profiles(id) on delete cascade,
  patient_id varchar,
  blood_group_id integer references public.blood_groups(id),
  emergency_contact_name varchar,
  emergency_contact_phone varchar,
  medical_history text,
  current_medications text,
  allergies text,
  assigned_doctor_id uuid,
  verification_status varchar default 'pending'
    check (verification_status in ('pending','verified','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.doctor_profiles (
  user_id uuid primary key references public.user_profiles(id) on delete cascade,
  medical_license varchar not null,
  qualification_id integer references public.qualifications(id),
  specialization varchar,
  experience_years integer,
  verification_status varchar default 'pending'
    check (verification_status in ('pending','verified','rejected')),
  is_active boolean default true,
  created_at timestamptz not null default now()
);

create table if not exists public.radiologist_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.user_profiles(id) on delete cascade,
  radiologist_license varchar not null,
  qualification_id integer references public.qualifications(id),
  imaging_expertise text not null,
  certifications text,
  experience_years integer not null default 0 check (experience_years >= 0),
  verification_status varchar default 'pending'
    check (verification_status in ('pending','verified','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_profiles (
  user_id uuid primary key references public.user_profiles(id) on delete cascade,
  employee_id varchar,
  department varchar,
  permissions jsonb default
    '{"manage_doctors": true, "manage_patients": true, "view_all_reports": true}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.doctor_patient_relationships (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid not null references public.doctor_profiles(user_id) on delete cascade,
  patient_id uuid not null references public.patient_profiles(user_id) on delete cascade,
  hospital_id uuid not null references public.hospitals(id) on delete cascade,
  relationship_status varchar not null default 'active'
    check (relationship_status in ('active','inactive','terminated')),
  assigned_by uuid references public.user_profiles(id) on delete set null,
  assigned_at timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint doctor_patient_unique_active unique (doctor_id, patient_id, hospital_id, relationship_status)
);

create index if not exists idx_dpr_doctor on public.doctor_patient_relationships(doctor_id);
create index if not exists idx_dpr_patient on public.doctor_patient_relationships(patient_id);
create index if not exists idx_dpr_hospital on public.doctor_patient_relationships(hospital_id);

-- updated_at trigger (shared)
create or replace function public.update_updated_at_column()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_dpr_updated_at on public.doctor_patient_relationships;
create trigger trg_dpr_updated_at before update on public.doctor_patient_relationships
  for each row execute function public.update_updated_at_column();

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at before update on public.user_profiles
  for each row execute function public.update_updated_at_column();

-- Helper functions used by legacy dashboards (harmless to keep).
create or replace function public.get_patient_doctor_count(patient_user_id uuid)
returns integer language sql stable as $$
  select count(*)::integer from public.doctor_patient_relationships
  where patient_id = patient_user_id and relationship_status = 'active';
$$;

create or replace function public.get_doctor_patient_count(doctor_user_id uuid)
returns integer language sql stable as $$
  select count(*)::integer from public.doctor_patient_relationships
  where doctor_id = doctor_user_id and relationship_status = 'active';
$$;

-- ---------------------------------------------------------------------
-- 4. RLS for the identity tables
--    The frontend AuthProvider reads user_profiles with the ANON client, so
--    authenticated users must be able to read profiles. Sensitive writes go
--    through the backend (service role, which bypasses RLS).
-- ---------------------------------------------------------------------
alter table public.hospitals              enable row level security;
alter table public.user_profiles          enable row level security;
alter table public.patient_profiles       enable row level security;
alter table public.doctor_profiles        enable row level security;
alter table public.radiologist_profiles   enable row level security;
alter table public.admin_profiles         enable row level security;
alter table public.doctor_patient_relationships enable row level security;
alter table public.blood_groups           enable row level security;
alter table public.qualifications         enable row level security;

-- A tiny helper macro isn't possible in SQL; repeat the two policies per table.
do $$
declare t text;
begin
  foreach t in array array[
    'hospitals','user_profiles','patient_profiles','doctor_profiles',
    'radiologist_profiles','admin_profiles','doctor_patient_relationships',
    'blood_groups','qualifications'
  ]
  loop
    execute format('drop policy if exists "authenticated_can_read" on public.%I', t);
    execute format(
      'create policy "authenticated_can_read" on public.%I for select using (auth.uid() is not null)', t);
  end loop;
end $$;

-- Users may update their own user_profiles row (used by profile screens).
drop policy if exists "users_update_own_profile" on public.user_profiles;
create policy "users_update_own_profile" on public.user_profiles
  for update using (auth.uid() = id);

-- ---------------------------------------------------------------------
-- 5. Unified analysis tables (from migrations 0001 + 0002)
-- ---------------------------------------------------------------------
create table if not exists public.analysis_sessions (
  id uuid primary key default gen_random_uuid(),
  modality text not null check (modality in ('eeg','mri')),
  analysis_type text not null,
  patient_id uuid not null references public.patient_profiles(user_id),
  doctor_id uuid references public.user_profiles(id),
  radiologist_id uuid references public.user_profiles(id),
  technician_id uuid references public.user_profiles(id),
  hospital_id uuid references public.hospitals(id),
  uploaded_by uuid references public.user_profiles(id),
  uploaded_by_role text,
  original_filename text not null,
  raw_file_path text,
  raw_file_bucket text,
  status text not null default 'queued',
  current_stage text,
  progress_percent integer not null default 0
    check (progress_percent >= 0 and progress_percent <= 100),
  error_message text,
  retry_count integer not null default 0,
  pipeline_options jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analysis_results (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.analysis_sessions(id) on delete cascade,
  prediction text not null,
  confidence numeric,
  probabilities jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  similarity jsonb not null default '{}'::jsonb,
  consistency jsonb not null default '{}'::jsonb,
  visualizations jsonb not null default '{}'::jsonb,
  model_version text,
  created_at timestamptz not null default now()
);

create table if not exists public.analysis_reports (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.analysis_sessions(id) on delete cascade,
  patient_pdf_url text,
  clinician_pdf_url text,
  technical_pdf_url text,
  asset_urls jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now()
);

create table if not exists public.job_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.analysis_sessions(id) on delete cascade,
  level text not null default 'info',
  stage text,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_analysis_sessions_patient_id on public.analysis_sessions(patient_id);
create index if not exists idx_analysis_sessions_status on public.analysis_sessions(status);
create index if not exists idx_analysis_sessions_modality on public.analysis_sessions(modality);
create index if not exists idx_analysis_sessions_hospital_id on public.analysis_sessions(hospital_id);
create index if not exists idx_analysis_results_session_id on public.analysis_results(session_id);
create index if not exists idx_analysis_reports_session_id on public.analysis_reports(session_id);
create index if not exists idx_job_events_session_id on public.job_events(session_id);
create unique index if not exists uq_analysis_results_session on public.analysis_results(session_id);
create unique index if not exists uq_analysis_reports_session on public.analysis_reports(session_id);

drop trigger if exists trg_analysis_sessions_updated_at on public.analysis_sessions;
create trigger trg_analysis_sessions_updated_at before update on public.analysis_sessions
  for each row execute function public.update_updated_at_column();

-- Analysis data is read via the backend API (service role), so RLS is
-- fail-closed here (no permissive policies) — the backend bypasses it.
alter table public.analysis_sessions enable row level security;
alter table public.analysis_results  enable row level security;
alter table public.analysis_reports  enable row level security;
alter table public.job_events         enable row level security;

-- ---------------------------------------------------------------------
-- 6. Private storage buckets
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public) values
  ('raw-files', 'raw-files', false),
  ('report-assets', 'report-assets', false),
  ('reports', 'reports', false),
  ('viewer-slices', 'viewer-slices', false)
on conflict (id) do nothing;

-- =====================================================================
-- DONE. Verify in the Table Editor that these tables exist:
--   hospitals, user_profiles, patient_profiles, doctor_profiles,
--   radiologist_profiles, admin_profiles, doctor_patient_relationships,
--   blood_groups, qualifications, analysis_sessions, analysis_results,
--   analysis_reports, job_events
-- and in Storage that these 4 private buckets exist:
--   raw-files, report-assets, reports, viewer-slices
-- =====================================================================
