"""Runs CAT12 (standalone SPM25 + MATLAB Runtime) segmentation on a raw T1
NIfTI and returns the paths to everything the rest of the pipeline needs:
mwp1/mwp2 (grey/white matter, modulated normalized -> ConViT input + report
images), p0 (tissue label map), and the two XML reports real volumetric
numbers are parsed from (see volumetric_analyzer.py).

The batch template mirrors CAT12's own ``standalone/cat_standalone_segment.m``
(shipped with every CAT12 standalone build) with two deliberate deviations:
surface reconstruction off (slow, not needed for volumetrics/classification)
and BIDS output off (keeps the simple ``mri/`` ``label/`` ``report/`` layout
next to the input file instead of a restructured derivatives tree).
"""

from __future__ import annotations

import logging
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

from app.pipelines.mri.config import CAT12_EXE, MCR_ROOT, CAT12_ROOT, CAT12_TIMEOUT_SECONDS

logger = logging.getLogger(__name__)

# ROI atlases: neuromorphometrics gives broad regional coverage (ventricles,
# lobes, subcortical structures); cobra adds detailed hippocampal/amygdala/
# cerebellar subfields. Both are fast relative to the segmentation itself.
_BATCH_TEMPLATE = """% CAT12 segmentation batch - generated by AI4NEURO cat12_manager.py
matlabbatch{{1}}.spm.tools.cat.estwrite.data = {{'{input_path},1'}};
matlabbatch{{1}}.spm.tools.cat.estwrite.nproc = 0;

matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.registration.vox = 1.5;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.registration.bb = 12;
matlabbatch{{1}}.spm.tools.cat.estwrite.opts.affreg = 'mni';
matlabbatch{{1}}.spm.tools.cat.estwrite.opts.biasstr = 0.5;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.APP = 1070;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.LASstr = 0.5;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.NCstr = -Inf;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.gcutstr = 2;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.cleanupstr = 0.5;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.restypes.optimal = [1 0.3];
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.setCOM = 1;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.affmod = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.WMHC = 2;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.segmentation.SLC = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.admin.lazy = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.admin.ignoreErrors = 1;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.admin.verb = 2;
matlabbatch{{1}}.spm.tools.cat.estwrite.extopts.admin.print = 2;

% Disabled: slow, not needed for volumetrics/classification.
matlabbatch{{1}}.spm.tools.cat.estwrite.output.surface = 0;

% Disabled: keep the flat mri/ label/ report/ layout next to the input file.
matlabbatch{{1}}.spm.tools.cat.estwrite.output.BIDS.BIDSno = 0;

% ROI atlases -> real regional volumes (hippocampus, ventricles, lobes, ...)
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.neuromorphometrics = 1;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.cobra = 1;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.lpba40 = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.hammers = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.ibsr = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.aal3 = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.mori = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.thalamus = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.thalamic_nuclei = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.suit = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.anatomy3 = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.julichbrain = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.Schaefer2018_100Parcels_17Networks_order = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.Schaefer2018_200Parcels_17Networks_order = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.Schaefer2018_400Parcels_17Networks_order = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.Schaefer2018_600Parcels_17Networks_order = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.ROImenu.atlases.ownatlas = {{''}};

% GM/WM modulated normalized maps: mwp1 -> ConViT input, mwp2 -> report image.
matlabbatch{{1}}.spm.tools.cat.estwrite.output.GM.native = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.GM.warped = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.GM.mod = 1;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.GM.dartel = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.WM.native = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.WM.warped = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.WM.mod = 1;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.WM.dartel = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.CSF.native = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.CSF.warped = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.CSF.mod = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.CSF.dartel = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.WMH.native = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.WMH.warped = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.WMH.mod = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.WMH.dartel = 0;

% p0 tissue label map (0=BG,1=CSF,2=GM,3=WM) - direct voxel-level cross-check.
matlabbatch{{1}}.spm.tools.cat.estwrite.output.label.native = 1;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.label.warped = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.label.dartel = 0;

matlabbatch{{1}}.spm.tools.cat.estwrite.output.bias.native = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.bias.warped = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.bias.dartel = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.las.native = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.las.warped = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.las.dartel = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.jacobianwarped = 0;
matlabbatch{{1}}.spm.tools.cat.estwrite.output.warps = [0 0];
"""


@dataclass
class Cat12Result:
    """Paths to everything CAT12 produced for one subject."""

    mwp1_path: str
    mwp2_path: str | None
    p0_path: str | None
    report_xml_path: str | None
    roi_xml_path: str | None


def validate_cat12_config() -> List[str]:
    """Return human-readable setup problems for CAT12/MATLAB Runtime."""
    issues: List[str] = []

    if not CAT12_ROOT:
        issues.append("CAT12_ROOT is not set.")
    elif not Path(CAT12_ROOT).exists():
        issues.append(f"CAT12_ROOT does not exist: {CAT12_ROOT}")

    if not CAT12_EXE:
        issues.append("CAT12_EXE is not set.")
    elif not Path(CAT12_EXE).exists():
        issues.append(f"CAT12_EXE does not exist: {CAT12_EXE}")

    if not MCR_ROOT:
        issues.append("MCR_ROOT is not set.")
    elif not Path(MCR_ROOT).exists():
        issues.append(f"MCR_ROOT does not exist: {MCR_ROOT}")

    return issues


def _write_segmentation_batch(input_nii_path: str, script_path: str) -> None:
    clean_path = input_nii_path.replace("\\", "/")
    with open(script_path, "w", encoding="utf-8") as handle:
        handle.write(_BATCH_TEMPLATE.format(input_path=clean_path))


def run_cat12_preprocessing(input_nii_path: str) -> Cat12Result | None:
    """Run CAT12 segmentation on ``input_nii_path`` in place.

    CAT12 writes outputs into ``mri/``, ``label/`` and ``report/``
    subdirectories next to the input file (BIDS output disabled above, so this
    layout is fixed regardless of CAT12 version). Returns ``None`` if CAT12
    isn't configured or the run fails; callers should treat that as a hard
    pipeline error, not silently fall back to unprocessed input.
    """
    input_nii_path = os.path.abspath(input_nii_path)

    config_issues = validate_cat12_config()
    if config_issues:
        logger.error("CAT12 is not configured: %s", " ".join(config_issues))
        return None

    work_dir = os.path.dirname(input_nii_path)
    filename = os.path.basename(input_nii_path)
    stem = filename
    for ext in (".nii.gz", ".nii"):
        if stem.lower().endswith(ext):
            stem = stem[: -len(ext)]
            break

    script_path = os.path.join(work_dir, "cat12_segment.m")
    _write_segmentation_batch(input_nii_path, script_path)

    # CAT12_EXE points at cat12_standalone.bat, which sets up the MCR PATH
    # itself before invoking spm25.exe - see that file for the wrapper.
    command = [CAT12_EXE, MCR_ROOT, "batch", script_path]

    logger.info("--- Starting CAT12 preprocessing on %s ---", filename)

    try:
        completed = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
            timeout=CAT12_TIMEOUT_SECONDS,
        )
        if completed.stdout:
            logger.info("CAT12 stdout (tail): %s", completed.stdout[-4000:])
        if completed.stderr:
            logger.info("CAT12 stderr (tail): %s", completed.stderr[-4000:])
    except subprocess.CalledProcessError as e:
        logger.error("CAT12 failed with exit code %s", e.returncode)
        if e.stdout:
            logger.error("CAT12 stdout (tail): %s", e.stdout[-4000:])
        if e.stderr:
            logger.error("CAT12 stderr (tail): %s", e.stderr[-4000:])
        return None
    except subprocess.TimeoutExpired:
        logger.error("CAT12 timed out after %ss on %s", CAT12_TIMEOUT_SECONDS, filename)
        return None

    mwp1_path = os.path.join(work_dir, "mri", f"mwp1{stem}.nii")
    mwp2_path = os.path.join(work_dir, "mri", f"mwp2{stem}.nii")
    p0_path = os.path.join(work_dir, "mri", f"p0{stem}.nii")
    report_xml_path = os.path.join(work_dir, "report", f"cat_{stem}.xml")
    roi_xml_path = os.path.join(work_dir, "label", f"catROI_{stem}.xml")

    if not os.path.exists(mwp1_path):
        logger.error("CAT12 finished but mwp1 output was not found: %s", mwp1_path)
        return None

    return Cat12Result(
        mwp1_path=mwp1_path,
        mwp2_path=mwp2_path if os.path.exists(mwp2_path) else None,
        p0_path=p0_path if os.path.exists(p0_path) else None,
        report_xml_path=report_xml_path if os.path.exists(report_xml_path) else None,
        roi_xml_path=roi_xml_path if os.path.exists(roi_xml_path) else None,
    )
